---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-64bit.deb
  - sudo dpkg -i hugo_0.74.3_Linux-64bit.deb
script:
  - hugo
  - cd public
  - git remote add master https://${GH_TOKEN}@github.com/ilyesAj/ilyesAj.github.io.git
  - git remote show origin
  - git add .
  - git commit -m "Rebuild site"
  - git push --force origin HEAD:master
